### ISSUE TITLE
Memory usage rises rapidly-Possible memory leak in window 7 

### ISSUE THREAD

**Issue by stavros92** [massej/RadioHLSConverter.backend.serverless#4]
It seems there is a memory leak in windows 7 . Memory usage rises progressively extremely high - very fast . In windows 10 there is no such problem.

**Comment by jonathanmassehsj** [comment]
Hi @stavros92,

Many thanks for your reporting.

It’s probably a memory leak from the NET Core from Windows 7, make sure you have the latest long-term NET Core version 6.

Which version of NET Core did you use on Windows 7?

**Comment by stavros92** [comment]
Hi! I am using dotnet v6.0.404 in windows 7 64bit. Memory usage gets crazy (> 1GB  after just an hour of usage and growing continuously....)

**Comment by jonathanmassehsj** [comment]
I did a fresh install of Windows 7 SP1 Pro x64 and installed dotnet v6.0.404.

I was not able to replicate the issue, it stayed at around 132 mb of memory for more than 4 hours.

![image](https://user-images.githubusercontent.com/49443479/210447463-d6a4f3bf-8437-4c1e-9ad3-32d013d3fbfb.png)

Did you have your appsettings.json configuration file by any chance? Maybe it's settings issue

**Comment by massej** [comment]
I just released version 1.0.13 which should help the memory issue you had, let me know if version 1.0.13 fix the issue

**Comment by stavros92** [comment]
Hello! Unfortunately the memory leak has not been resolved in the new version...(See update below screenshot-cause found).
I am attaching a screenshot after just 30 minutes where memory has climbed up to 1GB. In two other computers running windows 10 64bit the memory usage is stable and around just 35kb. I am also attaching my appsettings.json file (I have just altered the first station entry section url leaving the rest of the included demo file intact) 
![snap](https://user-images.githubusercontent.com/121773060/210511637-669ce0f1-ab6f-4a10-84fd-bdb00709c03c.png)
[appsettings.json.txt](https://github.com/massej/RadioHLSConverter.backend.serverless/files/10342444/appsettings.json.txt)

UPDATE!!!!! UPDATE!!!!! It seems I have finaly isolated the issue! Tried the latest winamp version (5.9xx) and the problem went away. I was using an old winamp version (5.52) . I do not know what could be the difference and what the player has to do with it, but apparently...it does!

**Comment by stavros92** [comment]
UPDATE 2. Unfortunetely although better, it seems that the memory leak still exists.... I left winamp running sure that everything is ok now, but I checked today (appr. 3days continyously playing) and the memory usage of radiohlsconverter was at 44 GB! (YEP 44 GB)!!!

**Comment by jonathanmassehsj** [comment]
44GB thats alot, mine stay at around 100 mb even after 24 hours of playing in Winamp.

Can you send me your configuration file, I will try to run it in my Windows 7 environment.

EDIT : I just saw your last post before with appsettings, I will try it and give you my result.

**Comment by stavros92** [comment]
I am attaching it again. I have also seen this maximum 44GB of memory usage when I was using the previous winamp version (whereas memory was climbing much faster). It seems that in my system where 64GB of ram is installed, windows prevents memory usage more than 44gb to the radiohlsconverter....

[appsettings.json.txt](https://github.com/massej/RadioHLSConverter.backend.serverless/files/10366847/appsettings.json.txt)

**Comment by massej** [comment]
Hi @stavros92,

I have a good news, I just replicated the issue with your config file and winamp 5.52.

Instead of creating a new buffer each time, I reuse the same buffer and it seems to fix the issue.

I just ran it for more than 1 hour and it's at around 30 mb.

You can try version 1.14 and let me know your result

**Comment by stavros92** [comment]
Hello! Sorry I was out of town and forgot to confirm that issue is resolved
and everything is working fine now! Thanks!
